// desprecated_web/src/components/GetStarted.tsx
import { useState } from 'react';
import { motion } from 'framer-motion';
import { Copy, Check, Terminal, FileText, Rocket, ArrowRight, Github } from 'lucide-react';

const steps = [
  {
    number: '01',
    title: 'Clone the repository',
    command: 'git clone https://github.com/kombihq/stackkits.git\ncd stackkits',
    description: 'Get the latest StackKits blueprints'
  },
  {
    number: '02',
    title: 'Copy the default spec',
    command: 'cp base-homelab/default-spec.yaml my-spec.yaml',
    description: 'Start with a ready-to-use template'
  },
  {
    number: '03',
    title: 'Configure your server',
    command: '# Edit my-spec.yaml\n# Set your server IP, SSH credentials, and domain',
    description: 'Customize for your environment'
  },
  {
    number: '04',
    title: 'Deploy',
    command: 'stackkit apply my-spec.yaml',
    description: 'One command to provision everything'
  }
];

function CodeBlock({ code, showCopy = true }: { code: string; showCopy?: boolean }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code.replace(/^#.*\n?/gm, '').trim());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="relative group">
      <pre className="bg-slate-900/70 rounded-lg p-4 text-sm overflow-x-auto">
        <code className="text-emerald-400">{code}</code>
      </pre>
      {showCopy && (
        <button
          onClick={handleCopy}
          className="absolute top-2 right-2 p-2 rounded-lg bg-slate-700/50 opacity-0 group-hover:opacity-100 transition-opacity hover:bg-slate-700"
        >
          {copied ? (
            <Check className="w-4 h-4 text-emerald-400" />
          ) : (
            <Copy className="w-4 h-4 text-slate-400" />
          )}
        </button>
      )}
    </div>
  );
}

export function GetStarted() {
  return (
    <section id="get-started" className="py-24 relative">
      {/* Background */}
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-cyan-500/5 to-transparent"></div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl sm:text-5xl font-bold text-white mb-4">
            Get <span className="gradient-text">Started</span>
          </h2>
          <p className="text-lg text-slate-400 max-w-2xl mx-auto">
            From zero to running homelab in four simple steps. No complex setup required.
          </p>
        </motion.div>

        {/* Quick Start Steps */}
        <div className="max-w-3xl mx-auto mb-16">
          <div className="space-y-6">
            {steps.map((step, index) => (
              <motion.div
                key={step.number}
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                className="glass rounded-xl p-6"
              >
                <div className="flex items-start gap-6">
                  <div className="flex-shrink-0">
                    <span className="text-3xl font-bold text-indigo-500/50">{step.number}</span>
                  </div>
                  <div className="flex-grow">
                    <h3 className="text-lg font-semibold text-white mb-2">{step.title}</h3>
                    <p className="text-sm text-slate-400 mb-4">{step.description}</p>
                    <CodeBlock code={step.command} />
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>

        {/* Additional Resources */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-16"
        >
          <a
            href="https://github.com/kombihq/stackkits/blob/main/docs/cli-reference.md"
            target="_blank"
            rel="noopener noreferrer"
            className="glass rounded-xl p-6 group hover:border-indigo-500/50 border border-transparent transition-all"
          >
            <Terminal className="w-8 h-8 text-indigo-400 mb-4" />
            <h3 className="text-lg font-semibold text-white mb-2 group-hover:text-indigo-400 transition-colors">
              CLI Reference
            </h3>
            <p className="text-sm text-slate-400 mb-4">
              Complete command documentation for power users
            </p>
            <span className="text-indigo-400 text-sm flex items-center gap-1 group-hover:gap-2 transition-all">
              Read docs <ArrowRight className="w-4 h-4" />
            </span>
          </a>

          <a
            href="https://github.com/kombihq/stackkits/blob/main/docs/creating-stackkits.md"
            target="_blank"
            rel="noopener noreferrer"
            className="glass rounded-xl p-6 group hover:border-cyan-500/50 border border-transparent transition-all"
          >
            <FileText className="w-8 h-8 text-cyan-400 mb-4" />
            <h3 className="text-lg font-semibold text-white mb-2 group-hover:text-cyan-400 transition-colors">
              Create Your Own
            </h3>
            <p className="text-sm text-slate-400 mb-4">
              Build custom StackKits for your specific needs
            </p>
            <span className="text-cyan-400 text-sm flex items-center gap-1 group-hover:gap-2 transition-all">
              Learn more <ArrowRight className="w-4 h-4" />
            </span>
          </a>

          <a
            href="https://github.com/kombihq/stackkits/blob/main/DEFAULT_SPECS_README.md"
            target="_blank"
            rel="noopener noreferrer"
            className="glass rounded-xl p-6 group hover:border-emerald-500/50 border border-transparent transition-all"
          >
            <Rocket className="w-8 h-8 text-emerald-400 mb-4" />
            <h3 className="text-lg font-semibold text-white mb-2 group-hover:text-emerald-400 transition-colors">
              Spec Templates
            </h3>
            <p className="text-sm text-slate-400 mb-4">
              Ready-to-use configuration templates
            </p>
            <span className="text-emerald-400 text-sm flex items-center gap-1 group-hover:gap-2 transition-all">
              View templates <ArrowRight className="w-4 h-4" />
            </span>
          </a>
        </motion.div>

        {/* CTA */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center"
        >
          <a
            href="https://github.com/kombihq/stackkits"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-3 px-8 py-4 bg-gradient-to-r from-indigo-500 to-cyan-500 rounded-xl text-white font-semibold hover:shadow-lg hover:shadow-indigo-500/25 transition-all"
          >
            <Github className="w-5 h-5" />
            View on GitHub
            <ArrowRight className="w-5 h-5" />
          </a>
        </motion.div>
      </div>
    </section>
  );
}

// website-v2/src/routes/get-started/+page.svelte
<script lang="ts">
	import { ArrowRight, Zap, Terminal, Github } from 'lucide-svelte';
	import ScrollReveal from '$lib/components/ScrollReveal.svelte';
	import CodeBlock from '$lib/components/CodeBlock.svelte';
	import TerminalDemo from '$lib/components/TerminalDemo.svelte';

	const detailedSteps = [
		{ number: '01', title: 'Clone the repository', command: 'git clone https://github.com/kombihq/stackkits.git\ncd stackkits' },
		{ number: '02', title: 'Copy the default spec', command: 'cp base-homelab/default-spec.yaml my-spec.yaml' },
		{ number: '03', title: 'Configure your server', command: '# Edit my-spec.yaml\n# Set your server IP, SSH credentials, and domain' },
		{ number: '04', title: 'Validate your configuration', command: 'stackkit validate my-spec.yaml' },
		{ number: '05', title: 'Deploy', command: 'stackkit apply my-spec.yaml' }
	];

	let showDetailed = $state(false);
</script>

<svelte:head>
	<title>Get Started - kombify StackKits</title>
	<meta name="description" content="Get started with StackKits. From zero to running homelab in two simple commands." />
</svelte:head>

<!-- Header -->
<section class="py-16 border-b border-border">
	<div class="max-w-6xl mx-auto px-6">
		<ScrollReveal>
			<div class="text-center">
				<h1 class="text-4xl font-bold">Get Started</h1>
				<p class="mt-4 text-lg text-muted-foreground max-w-2xl mx-auto">
					From zero to running homelab in two simple commands.
				</p>
			</div>
		</ScrollReveal>
	</div>
</section>

<!-- Core Message -->
<section class="py-12 border-b border-border bg-primary/5">
	<div class="max-w-4xl mx-auto px-6 text-center">
		<ScrollReveal>
			<Zap class="w-12 h-12 text-primary mx-auto mb-4" />
			<h2 class="text-3xl font-bold mb-4">
				Run One Command. Your Homelab Stands.
			</h2>
			<p class="text-lg text-muted-foreground">
				That's our vision: A CLI tool that makes infrastructure deployment as simple as possible.
			</p>
		</ScrollReveal>
	</div>
</section>

<!-- Quick Start -->
<section class="py-16">
	<div class="max-w-4xl mx-auto px-6">
		<ScrollReveal>
			<div class="text-center mb-12">
				<h2 class="text-2xl font-bold mb-4">The Simple Way</h2>
				<p class="text-muted-foreground">Two commands to deploy your entire homelab.</p>
			</div>
		</ScrollReveal>

		<ScrollReveal delay={0.1}>
			<div class="grid md:grid-cols-2 gap-6 mb-12">
				<div class="card p-8 text-center border-primary/20">
					<div class="text-5xl font-bold text-primary/20 mb-4">01</div>
					<h3 class="text-xl font-semibold mb-3">Prepare your environment</h3>
					<div class="card p-4 font-mono text-sm text-primary">$ stackkit prepare</div>
					<p class="text-muted-foreground text-sm mt-4">
						Validates dependencies and sets up your local environment.
					</p>
				</div>

				<div class="card p-8 text-center border-primary/20">
					<div class="text-5xl font-bold text-primary/20 mb-4">02</div>
					<h3 class="text-xl font-semibold mb-3">Initialize your homelab</h3>
					<div class="card p-4 font-mono text-sm text-primary">$ stackkit init</div>
					<p class="text-muted-foreground text-sm mt-4">
						Deploys your complete infrastructure - that's it!
					</p>
				</div>
			</div>
		</ScrollReveal>

		<div class="text-center">
			<button
				onclick={() => (showDetailed = !showDetailed)}
				class="text-primary hover:text-primary/80 font-medium text-sm"
			>
				{showDetailed ? 'Hide detailed steps' : 'Show current detailed steps'}
			</button>
		</div>
	</div>
</section>

<!-- Detailed Steps -->
{#if showDetailed}
	<section class="py-16 bg-card/30">
		<div class="max-w-3xl mx-auto px-6">
			<div class="text-center mb-12">
				<h2 class="text-2xl font-bold mb-4">Current Process</h2>
				<p class="text-muted-foreground">
					Here's how it works today - we're working towards simplifying this.
				</p>
			</div>

			<div class="space-y-6">
				{#each detailedSteps as step, i}
					<ScrollReveal delay={i * 0.1}>
						<div class="card p-8 flex gap-6">
							<div class="flex-shrink-0">
								<div class="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center">
									<span class="text-primary font-bold text-sm">{step.number}</span>
								</div>
							</div>
							<div class="flex-1">
								<h3 class="text-xl font-semibold mb-3">{step.title}</h3>
								<CodeBlock command={step.command} />
							</div>
						</div>
					</ScrollReveal>
				{/each}
			</div>

			<ScrollReveal delay={0.5}>
				<div class="mt-12 alert">
					<Terminal class="w-6 h-6 text-primary flex-shrink-0" />
					<div>
						<h4 class="font-semibold mb-2">Need Help?</h4>
						<p class="text-sm text-muted-foreground mb-4">
							Check the documentation or join our community for support.
						</p>
						<a
							href="https://github.com/kombihq/stackkits"
							target="_blank"
							rel="noopener"
							class="btn btn-primary btn-sm"
						>
							<Github class="w-4 h-4" />
							View on GitHub
						</a>
					</div>
				</div>
			</ScrollReveal>
		</div>
	</section>
{/if}

<!-- Why StackKits -->
<section class="py-16">
	<div class="max-w-6xl mx-auto px-6">
		<ScrollReveal>
			<h2 class="text-3xl font-bold text-center mb-12">Why StackKits?</h2>
		</ScrollReveal>

		<div class="grid md:grid-cols-3 gap-8">
			<ScrollReveal delay={0.1}>
				<div class="text-center">
					<div class="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
						<Zap class="w-8 h-8 text-primary" />
					</div>
					<h3 class="text-xl font-semibold mb-2">Lightning Fast</h3>
					<p class="text-muted-foreground">
						Deploy complex infrastructure in minutes, not hours or days.
					</p>
				</div>
			</ScrollReveal>

			<ScrollReveal delay={0.2}>
				<div class="text-center">
					<div class="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
						<Terminal class="w-8 h-8 text-primary" />
					</div>
					<h3 class="text-xl font-semibold mb-2">Simple CLI</h3>
					<p class="text-muted-foreground">
						No complex configurations. Just simple, intuitive commands.
					</p>
				</div>
			</ScrollReveal>

			<ScrollReveal delay={0.3}>
				<div class="text-center">
					<div class="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
						<Github class="w-8 h-8 text-primary" />
					</div>
					<h3 class="text-xl font-semibold mb-2">Open Source</h3>
					<p class="text-muted-foreground">
						Community-driven, transparent, and free to use and modify.
					</p>
				</div>
			</ScrollReveal>
		</div>
	</div>
</section>

<!-- CTA -->
<section class="py-16 bg-card/50 border-t border-border">
	<div class="max-w-4xl mx-auto px-6 text-center">
		<ScrollReveal>
			<h2 class="text-3xl font-bold mb-4">Ready to Start?</h2>
			<p class="text-muted-foreground mb-8">
				Join developers building better homelabs with StackKits.
			</p>
			<a href="/how-it-works" class="btn btn-primary btn-lg">
				Learn How It Works
				<ArrowRight class="w-5 h-5" />
			</a>
		</ScrollReveal>
	</div>
</section>
