// website-v2/src/routes/get-started/+page.svelte
<script lang="ts">
	import { ArrowRight, Zap, Terminal, Github } from 'lucide-svelte';
	import ScrollReveal from '$lib/components/ScrollReveal.svelte';
	import CodeBlock from '$lib/components/CodeBlock.svelte';
	import TerminalDemo from '$lib/components/TerminalDemo.svelte';

	const detailedSteps = [
		{ number: '01', title: 'Clone the repository', command: 'git clone https://github.com/kombifyio/stackkits.git\ncd stackkits' },
		{ number: '02', title: 'Copy the default spec', command: 'cp base/default-spec.yaml my-spec.yaml' },
		{ number: '03', title: 'Configure your server', command: '# Edit my-spec.yaml\n# Set your server IP, SSH credentials, and domain' },
		{ number: '04', title: 'Validate your configuration', command: 'stackkit validate my-spec.yaml' },
		{ number: '05', title: 'Deploy', command: 'stackkit apply my-spec.yaml' }
	];

	let showDetailed = $state(false);
</script>

<svelte:head>
	<title>Get Started - kombify StackKits</title>
	<meta name="description" content="Get started with StackKits. From zero to running homelab in two simple commands." />
</svelte:head>

<!-- Header -->
<section class="py-16 border-b border-border">
	<div class="max-w-6xl mx-auto px-6">
		<ScrollReveal>
			<div class="text-center">
				<h1 class="text-4xl font-bold">Get Started</h1>
				<p class="mt-4 text-lg text-muted-foreground max-w-2xl mx-auto">
					From zero to running homelab in two simple commands.
				</p>
			</div>
		</ScrollReveal>
	</div>
</section>

<!-- Core Message -->
<section class="py-12 border-b border-border bg-primary/5">
	<div class="max-w-4xl mx-auto px-6 text-center">
		<ScrollReveal>
			<Zap class="w-12 h-12 text-primary mx-auto mb-4" />
			<h2 class="text-3xl font-bold mb-4">
				Run One Command. Your Homelab Stands.
			</h2>
			<p class="text-lg text-muted-foreground">
				That's our vision: A CLI tool that makes infrastructure deployment as simple as possible.
			</p>
		</ScrollReveal>
	</div>
</section>

<!-- Quick Start -->
<section class="py-16">
	<div class="max-w-4xl mx-auto px-6">
		<ScrollReveal>
			<div class="text-center mb-12">
				<h2 class="text-2xl font-bold mb-4">The Simple Way</h2>
				<p class="text-muted-foreground">Two commands to deploy your entire homelab.</p>
			</div>
		</ScrollReveal>

		<ScrollReveal delay={0.1}>
			<div class="grid md:grid-cols-2 gap-6 mb-12">
				<div class="card p-8 text-center border-primary/20">
					<div class="text-5xl font-bold text-primary/20 mb-4">01</div>
					<h3 class="text-xl font-semibold mb-3">Prepare your environment</h3>
					<div class="card p-4 font-mono text-sm text-primary">$ stackkit prepare</div>
					<p class="text-muted-foreground text-sm mt-4">
						Validates dependencies and sets up your local environment.
					</p>
				</div>

				<div class="card p-8 text-center border-primary/20">
					<div class="text-5xl font-bold text-primary/20 mb-4">02</div>
					<h3 class="text-xl font-semibold mb-3">Initialize your homelab</h3>
					<div class="card p-4 font-mono text-sm text-primary">$ stackkit init</div>
					<p class="text-muted-foreground text-sm mt-4">
						Deploys your complete infrastructure - that's it!
					</p>
				</div>
			</div>
		</ScrollReveal>

		<div class="text-center">
			<button
				onclick={() => (showDetailed = !showDetailed)}
				class="text-primary hover:text-primary/80 font-medium text-sm"
			>
				{showDetailed ? 'Hide detailed steps' : 'Show current detailed steps'}
			</button>
		</div>
	</div>
</section>

<!-- Detailed Steps -->
{#if showDetailed}
	<section class="py-16 bg-card/30">
		<div class="max-w-3xl mx-auto px-6">
			<div class="text-center mb-12">
				<h2 class="text-2xl font-bold mb-4">Current Process</h2>
				<p class="text-muted-foreground">
					Here's how it works today - we're working towards simplifying this.
				</p>
			</div>

			<div class="space-y-6">
				{#each detailedSteps as step, i}
					<ScrollReveal delay={i * 0.1}>
						<div class="card p-8 flex gap-6">
							<div class="flex-shrink-0">
								<div class="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center">
									<span class="text-primary font-bold text-sm">{step.number}</span>
								</div>
							</div>
							<div class="flex-1">
								<h3 class="text-xl font-semibold mb-3">{step.title}</h3>
								<CodeBlock command={step.command} />
							</div>
						</div>
					</ScrollReveal>
				{/each}
			</div>

			<ScrollReveal delay={0.5}>
				<div class="mt-12 alert">
					<Terminal class="w-6 h-6 text-primary flex-shrink-0" />
					<div>
						<h4 class="font-semibold mb-2">Need Help?</h4>
						<p class="text-sm text-muted-foreground mb-4">
							Check the documentation or join our community for support.
						</p>
						<a
							href="https://github.com/kombifyio/stackkits"
							target="_blank"
							rel="noopener"
							class="btn btn-primary btn-sm"
						>
							<Github class="w-4 h-4" />
							View on GitHub
						</a>
					</div>
				</div>
			</ScrollReveal>
		</div>
	</section>
{/if}

<!-- Why StackKits -->
<section class="py-16">
	<div class="max-w-6xl mx-auto px-6">
		<ScrollReveal>
			<h2 class="text-3xl font-bold text-center mb-12">Why StackKits?</h2>
		</ScrollReveal>

		<div class="grid md:grid-cols-3 gap-8">
			<ScrollReveal delay={0.1}>
				<div class="text-center">
					<div class="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
						<Zap class="w-8 h-8 text-primary" />
					</div>
					<h3 class="text-xl font-semibold mb-2">Lightning Fast</h3>
					<p class="text-muted-foreground">
						Deploy complex infrastructure in minutes, not hours or days.
					</p>
				</div>
			</ScrollReveal>

			<ScrollReveal delay={0.2}>
				<div class="text-center">
					<div class="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
						<Terminal class="w-8 h-8 text-primary" />
					</div>
					<h3 class="text-xl font-semibold mb-2">Simple CLI</h3>
					<p class="text-muted-foreground">
						No complex configurations. Just simple, intuitive commands.
					</p>
				</div>
			</ScrollReveal>

			<ScrollReveal delay={0.3}>
				<div class="text-center">
					<div class="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
						<Github class="w-8 h-8 text-primary" />
					</div>
					<h3 class="text-xl font-semibold mb-2">Open Source</h3>
					<p class="text-muted-foreground">
						Community-driven, transparent, and free to use and modify.
					</p>
				</div>
			</ScrollReveal>
		</div>
	</div>
</section>

<!-- CTA -->
<section class="py-16 bg-card/50 border-t border-border">
	<div class="max-w-4xl mx-auto px-6 text-center">
		<ScrollReveal>
			<h2 class="text-3xl font-bold mb-4">Ready to Start?</h2>
			<p class="text-muted-foreground mb-8">
				Join developers building better homelabs with StackKits.
			</p>
			<a href="/how-it-works" class="btn btn-primary btn-lg">
				Learn How It Works
				<ArrowRight class="w-5 h-5" />
			</a>
		</ScrollReveal>
	</div>
</section>

// marketing/src/pages/GetStarted.tsx
import { ArrowRight, Download, BookOpen, MessageSquare, Github } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Navbar } from '../components/Navbar';
import { Footer } from '../components/Footer';
import { Card } from '../components/Card';
import { Button } from '../components/Button';

const quickStartSteps = [
  {
    title: 'Clone the Repository',
    description: 'Get the StackKits code from GitHub and explore available StackKits.',
    icon: <Github size={32} className="text-orange-600" />
  },
  {
    title: 'Install Prerequisites',
    description: 'Ensure Docker and OpenTofu are installed on your system.',
    icon: <Download size={32} className="text-green-600" />
  },
  {
    title: 'Choose Your StackKit',
    description: 'Select Base, Modern, or HA StackKit based on your needs.',
    icon: <BookOpen size={32} className="text-gray-600" />
  },
  {
    title: 'Deploy & Enjoy',
    description: 'Run the deployment commands and start using your new infrastructure.',
    icon: <MessageSquare size={32} className="text-gray-600" />
  }
];

const resources = [
  {
    title: 'Documentation',
    description: 'Comprehensive guides and reference documentation for all StackKits.',
    link: '#',
    icon: <BookOpen size={24} />
  },
  {
    title: 'GitHub Repository',
    description: 'Source code, issues, and contribution guidelines.',
    link: 'https://github.com/stackkits',
    icon: <Github size={24} />
  },
  {
    title: 'Community Support',
    description: 'Get help from the community and share your experiences.',
    link: '#',
    icon: <MessageSquare size={24} />
  }
];

export function GetStarted() {
  return (
    <div className="min-h-screen bg-white">
      <Navbar />
      <main>
        {/* Section Header */}
        <section className="section-padding bg-white">
          <div className="container-custom">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
                Get Started Today
              </h2>
              <p className="text-lg text-gray-600 max-w-2xl mx-auto">
                Ready to build your homelab? Follow these simple steps to get started with StackKits.
              </p>
            </div>

            {/* Quick Start Steps */}
            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 mb-16">
              {quickStartSteps.map((step, index) => (
                <Card key={index} className="text-center">
                  <div className="flex justify-center mb-4">
                    <div className="p-4 bg-gray-50 rounded-xl">
                      {step.icon}
                    </div>
                  </div>
                  <h3 className="text-lg font-bold text-gray-900 mb-2">
                    {step.title}
                  </h3>
                  <p className="text-gray-600 text-sm">
                    {step.description}
                  </p>
                </Card>
              ))}
            </div>

            {/* CTA Section */}
            <Card hover={false} className="p-8 md:p-12 mb-16">
              <div className="grid md:grid-cols-2 gap-8 items-center">
                <div>
                  <h3 className="text-2xl md:text-3xl font-bold text-gray-900 mb-4">
                    Ready to Deploy Your First StackKit?
                  </h3>
                  <p className="text-gray-600 mb-6">
                    Start with Base Homelab - the perfect starting point for single-server deployments. 
                    It includes everything you need to get started with your self-hosted infrastructure.
                  </p>
                  <div className="flex flex-col sm:flex-row gap-4">
                    <a
                      href="https://github.com/stackkits"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex items-center space-x-2"
                    >
                      <Button variant="primary" size="md" className="flex items-center space-x-2">
                        <span>View on GitHub</span>
                        <ArrowRight size={20} />
                      </Button>
                    </a>
                    <Link to="/overview">
                      <Button variant="secondary" size="md" className="flex items-center space-x-2">
                        <span>Explore StackKits</span>
                      </Button>
                    </Link>
                  </div>
                </div>
                <div className="bg-gradient-to-br from-orange-500 to-orange-600 rounded-xl p-8 text-white text-center">
                  <div className="text-5xl font-bold mb-2">Free</div>
                  <div className="text-xl mb-4">Open Source</div>
                  <p className="text-orange-100">
                    StackKits is completely free and open source. 
                    Use it, modify it, and contribute back to the community.
                  </p>
                </div>
              </div>
            </Card>

            {/* Resources */}
            <div>
              <h3 className="text-2xl font-bold text-gray-900 mb-8 text-center">
                Additional Resources
              </h3>
              <div className="grid md:grid-cols-3 gap-6">
                {resources.map((resource, index) => (
                  <a
                    key={index}
                    href={resource.link}
                    target={resource.link.startsWith('http') ? '_blank' : undefined}
                    rel={resource.link.startsWith('http') ? 'noopener noreferrer' : undefined}
                    className="block"
                  >
                    <Card className="group">
                      <div className="flex items-start space-x-4 mb-4">
                        <div className="p-3 bg-orange-50 rounded-lg text-orange-600 group-hover:bg-orange-600 group-hover:text-white transition-colors">
                          {resource.icon}
                        </div>
                        <div className="flex-1">
                          <h4 className="font-semibold text-gray-900 mb-2">
                            {resource.title}
                          </h4>
                          <p className="text-sm text-gray-600">
                            {resource.description}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center text-orange-600 font-medium text-sm group-hover:translate-x-2 transition-transform">
                        <span>Learn More</span>
                        <ArrowRight size={16} className="ml-1" />
                      </div>
                    </Card>
                  </a>
                ))}
              </div>
            </div>

            {/* Community Note */}
            <div className="mt-12 bg-gradient-to-r from-orange-50 to-orange-100 rounded-2xl p-8">
              <div className="flex flex-col md:flex-row items-center justify-between gap-6">
                <div className="flex-1">
                  <h4 className="text-xl font-bold text-gray-900 mb-2">
                    Join Our Community
                  </h4>
                  <p className="text-gray-600">
                    Connect with other homelab enthusiasts, share your setups, and get help when you need it. 
                    Our community is growing every day!
                  </p>
                </div>
                <a
                  href="#"
                  className="flex items-center space-x-2 whitespace-nowrap"
                >
                  <Button variant="primary" size="md" className="flex items-center space-x-2">
                    <MessageSquare size={20} />
                    <span>Join Community</span>
                  </Button>
                </a>
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
